# Generated by Django 2.1.3 on 2018-11-06 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('power_in', models.IntegerField(default=0)),
                ('power_out', models.IntegerField(default=0)),
                ('energy', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Power Projects',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('mode', models.CharField(max_length=255, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='power_app.Project')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('formula', models.CharField(max_length=255, null=True)),
                ('file', models.FileField(upload_to='excel')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='power_app.Service')),
            ],
            options={
                'verbose_name_plural': 'Values',
            },
        ),
    ]
